language: python
python: 3.7
branches:
  except:
  - gh-pages

install:
- pip install mkdocs mkdocs-bootstrap

script:
- mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: site
  target_branch: gh-pages
  on:
    branch: master
  github_token: $GITHUB_TOKEN
